apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command:
        - "/bin/sh"
        - "-c"
        - |
          env
          ls /usr/configs
          cat /usr/configs/example.property.file
      envFrom:
        - configMapRef:
            name: special-config
      resources:
        limits:
          cpu: "250m"
          memory: "64Mi"
      volumeMounts:
        - name: config-files
          mountPath: /usr/configs
          readOnly: true
  volumes:
    - name: config-files
      configMap:
        name: special-config-files
  restartPolicy: Never
